name: Publish Python Package

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to PyPI
      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: ${{secrets.PYPI_TOKEN_NAME}}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*
